output_dir: ${SCRATCH}/heptrkx/results/gnnsegclf_big_000

trainer:
    name: gnn
    real_weight: 5.0   # 0.5 / 0.1
    fake_weight: 0.555 # 0.5 / 0.9

data:
    name: hitgraphs
    input_dir: ${SCRATCH}/heptrkx/data/hitgraphs_big_000
    n_train: 16384
    n_valid: 1024
    batch_size: 2
    n_workers: 4

model:
    name: 'gnn_segment_classifier'
    input_dim: 3
    hidden_dim: 128
    n_iters: 6
    loss_func: 'binary_cross_entropy'
    optimizer: 'Adam'
    learning_rate: 0.001

training:
    n_epochs: 32
