output_dir: ${SCRATCH}/heptrkx/results/gnnsegclf_small_000

trainer:
    name: gnn

data:
    name: hitgraphs
    input_dir: ${SCRATCH}/heptrkx/data/hitgraphs_small_000
    n_train: 1024 #8192
    n_valid: 1024
    batch_size: 1
    n_workers: 8

model:
    name: 'gnn_segment_classifier'
    input_dim: 3
    hidden_dim: 32
    n_iters: 4
    loss_func: 'binary_cross_entropy'
    optimizer: 'Adam'
    learning_rate: 0.001

training:
    n_epochs: 16
